### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by makoto323** [makoto323/chat-space#8]
# IPアドレス
3.113.211.27

**Comment by yasunamiura** [comment]
荒井さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①グループ名と最新メッセージの下線を消しましょう
②画像も線に合わせて先頭になるように位置を調整しましょう**
<img width="1257" alt="ChatSpace" src="https://user-images.githubusercontent.com/52514431/80164447-f4560480-8613-11ea-8233-578605ab272e.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by makoto323** [comment]
三浦さん、ご確認ありがとうございます。
早速修正させていただきましたので、再度ご確認お願いいたします。

[修正箇所]
①グループ名と最新メッセージの下線を消しましょう
→リンクの下線を見えないように修正しました。

②画像も線に合わせて先頭になるように位置を調整しましょう
→他のメッセージテキストと同様の位置に修正しました。

お手数ですが、よろしくお願いします！

**Comment by mo1015** [comment]
再提出ありがとうございます！

**①グループ名と最新メッセージの下線を消しましょう**
→修正確認ができました！

**②画像も線に合わせて先頭になるように位置を調整しましょう**
→こちらは修正確認ができませんでした。
（リロードすると位置が修正されますが、投稿された時点では前回と同じ位置に表示されます）
本番環境で実装できているかもう一度確認をお願いします！


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by makoto323** [comment]
確認ありがとうございます！

②画像も線に合わせて先頭になるように位置を調整しましょう
→scssファイルのみの修正で、jsファイルのimageにクラスが当たっていませんでした。

再度修正して確認しましたので、もう一度確認をお願いいたします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
